/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz.VIEW;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quiz.DAO.PartidaDAO;
import quiz.DAO.QuestaoDAO;
import quiz.VO.Partida;
import quiz.DAO.TemaDAO;
import quiz.DAO.UsuarioDAO;
import quiz.VO.Alternativa;
import quiz.VO.Questao;
import quiz.VO.Tema;
import quiz.VO.Usuario;


public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    
    private ArrayList<Partida> partidas;
    private Partida partidaselecionada;
    
    private ArrayList<Tema> temas;
    private Tema temaSelecionado;
    
    private ArrayList<Questao> questoes;
    private Questao questao;
    private int iQuestao=0;
    private int corretas=0;
    
    private ArrayList<Alternativa> alternativas;
    private Alternativa alt1;
    private Alternativa alt2;    
    private Alternativa alt3;
    private Alternativa alt4;    
    
    public Quiz() {
        initComponents();
        this.setTitle("Jogo Quiz");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        PartidaDAO pDAO = new PartidaDAO();
        TemaDAO tDAO = new TemaDAO();
        
        this.partidas = pDAO.carregarPartidas();
        this.temas = tDAO.cosultarTema();
        
        DefaultComboBoxModel modeloComboPartidas = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloComboTemas = new DefaultComboBoxModel();
        
        modeloComboPartidas.addAll(partidas);
        modeloComboTemas.addAll(temas);
        
        ComboBoxPartida.setModel(modeloComboPartidas);  
        ComboBoxTemas.setModel(modeloComboTemas);
        
    }

    private void CarregaQuestao()
    {
           questao = questoes.get(iQuestao);
            alternativas = questao.getAlternativas();
            FieldPergunta.setText(questao.getQuestao());
             alt1 = alternativas.get(0);
            RadioAlternativa1.setText(alt1.toString());
             alt2 = alternativas.get(1);
            RadioAlternativa2.setText(alt2.toString());
             alt3 = alternativas.get(2);
            RadioAlternativa3.setText(alt3.toString());
             alt4 = alternativas.get(3);
            RadioAlternativa4.setText(alt4.toString());  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alternativas = new javax.swing.ButtonGroup();
        Cabecalho = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Base = new javax.swing.JTabbedPane();
        Menu = new javax.swing.JPanel();
        BtnCriarPartida = new javax.swing.JButton();
        BtnCarregarPartida = new javax.swing.JButton();
        BtnRanking = new javax.swing.JButton();
        CriarPartida = new javax.swing.JPanel();
        ComboBoxTemas = new javax.swing.JComboBox<>();
        ComboBoxDificuldade = new javax.swing.JComboBox<>();
        BtnCriar = new javax.swing.JButton();
        BtnVoltar2 = new javax.swing.JButton();
        SpingQuestoes = new javax.swing.JSpinner();
        CarregarPartida = new javax.swing.JPanel();
        ComboBoxPartida = new javax.swing.JComboBox<>();
        BtnCarregar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        Pergunta = new javax.swing.JPanel();
        FieldPergunta = new javax.swing.JTextField();
        RadioAlternativa1 = new javax.swing.JRadioButton();
        RadioAlternativa2 = new javax.swing.JRadioButton();
        RadioAlternativa3 = new javax.swing.JRadioButton();
        RadioAlternativa4 = new javax.swing.JRadioButton();
        BtnSair = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();
        Final = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FieldNome = new javax.swing.JTextField();
        TextPontos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnSair2 = new javax.swing.JButton();
        Ranking1 = new javax.swing.JPanel();
        PaneUsuarios = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BtnVoltar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabecalho.setBackground(new java.awt.Color(60, 63, 240));

        Titulo.setBackground(new java.awt.Color(255, 0, 0));
        Titulo.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        Titulo.setText("QUIZ");

        javax.swing.GroupLayout CabecalhoLayout = new javax.swing.GroupLayout(Cabecalho);
        Cabecalho.setLayout(CabecalhoLayout);
        CabecalhoLayout.setHorizontalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabecalhoLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        CabecalhoLayout.setVerticalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabecalhoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(26, 26, 26))
        );

        getContentPane().add(Cabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 821, -1));

        Base.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        BtnCriarPartida.setText("Criar nova Partida");
        BtnCriarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarPartidaActionPerformed(evt);
            }
        });

        BtnCarregarPartida.setText("Carregar Partida");
        BtnCarregarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarPartidaActionPerformed(evt);
            }
        });

        BtnRanking.setText("Ranking");
        BtnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarregarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCriarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(BtnCriarPartida)
                .addGap(34, 34, 34)
                .addComponent(BtnCarregarPartida)
                .addGap(30, 30, 30)
                .addComponent(BtnRanking)
                .addGap(162, 162, 162))
        );

        Base.addTab("tab1", Menu);

        ComboBoxTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTemasActionPerformed(evt);
            }
        });

        ComboBoxDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        ComboBoxDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDificuldadeActionPerformed(evt);
            }
        });

        BtnCriar.setText("Criar");
        BtnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarActionPerformed(evt);
            }
        });

        BtnVoltar2.setText("Voltar");
        BtnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CriarPartidaLayout = new javax.swing.GroupLayout(CriarPartida);
        CriarPartida.setLayout(CriarPartidaLayout);
        CriarPartidaLayout.setHorizontalGroup(
            CriarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarPartidaLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(ComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SpingQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarPartidaLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(BtnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
            .addGroup(CriarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarPartidaLayout.createSequentialGroup()
                    .addContainerGap(355, Short.MAX_VALUE)
                    .addComponent(BtnVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(350, 350, 350)))
        );
        CriarPartidaLayout.setVerticalGroup(
            CriarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarPartidaLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(CriarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpingQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(BtnCriar)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(CriarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarPartidaLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(BtnVoltar2)
                    .addGap(131, 131, 131)))
        );

        Base.addTab("tab1", CriarPartida);

        ComboBoxPartida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnCarregar.setText("Carregar Partida");
        BtnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarregarPartidaLayout = new javax.swing.GroupLayout(CarregarPartida);
        CarregarPartida.setLayout(CarregarPartidaLayout);
        CarregarPartidaLayout.setHorizontalGroup(
            CarregarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregarPartidaLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(CarregarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ComboBoxPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        CarregarPartidaLayout.setVerticalGroup(
            CarregarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregarPartidaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(ComboBoxPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(BtnCarregar)
                .addGap(64, 64, 64)
                .addComponent(BtnVoltar)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        Base.addTab("tab1", CarregarPartida);

        FieldPergunta.setEditable(false);
        FieldPergunta.setText("jTextField1");

        Alternativas.add(RadioAlternativa1);
        RadioAlternativa1.setText("jRadioButton1");
        RadioAlternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlternativa1ActionPerformed(evt);
            }
        });

        Alternativas.add(RadioAlternativa2);
        RadioAlternativa2.setText("jRadioButton1");
        RadioAlternativa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlternativa2ActionPerformed(evt);
            }
        });

        Alternativas.add(RadioAlternativa3);
        RadioAlternativa3.setText("jRadioButton1");
        RadioAlternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlternativa3ActionPerformed(evt);
            }
        });

        Alternativas.add(RadioAlternativa4);
        RadioAlternativa4.setText("jRadioButton1");
        RadioAlternativa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlternativa4ActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair e Salvar");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PerguntaLayout = new javax.swing.GroupLayout(Pergunta);
        Pergunta.setLayout(PerguntaLayout);
        PerguntaLayout.setHorizontalGroup(
            PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerguntaLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioAlternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioAlternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioAlternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioAlternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerguntaLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerguntaLayout.createSequentialGroup()
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerguntaLayout.createSequentialGroup()
                        .addComponent(FieldPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
            .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PerguntaLayout.createSequentialGroup()
                    .addGap(352, 352, 352)
                    .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );
        PerguntaLayout.setVerticalGroup(
            PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerguntaLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(FieldPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioAlternativa3)
                    .addComponent(RadioAlternativa1))
                .addGap(85, 85, 85)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioAlternativa4)
                    .addComponent(RadioAlternativa2))
                .addGap(100, 100, 100)
                .addComponent(BtnSair)
                .addGap(27, 27, 27))
            .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerguntaLayout.createSequentialGroup()
                    .addContainerGap(383, Short.MAX_VALUE)
                    .addComponent(BtnConfirmar)
                    .addGap(59, 59, 59)))
        );

        Base.addTab("tab1", Pergunta);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("PARABENS");

        FieldNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        TextPontos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextPontos.setText("pontos");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Digite seu nome:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Pontuação:");

        BtnSair2.setText("Sair e Salvar");
        BtnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinalLayout = new javax.swing.GroupLayout(Final);
        Final.setLayout(FinalLayout);
        FinalLayout.setHorizontalGroup(
            FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalLayout.createSequentialGroup()
                .addGroup(FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FinalLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(FieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel5))
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(TextPontos))
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(BtnSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        FinalLayout.setVerticalGroup(
            FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(FieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextPontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(BtnSair2)
                .addGap(52, 52, 52))
        );

        Base.addTab("tab1", Final);

        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Pontuação", "Total de Questões"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaneUsuarios.setViewportView(TableUsuarios);

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel2.setText("Nossos Jogadores");

        BtnVoltar3.setText("Voltar");
        BtnVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ranking1Layout = new javax.swing.GroupLayout(Ranking1);
        Ranking1.setLayout(Ranking1Layout);
        Ranking1Layout.setHorizontalGroup(
            Ranking1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(BtnVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(Ranking1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PaneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        Ranking1Layout.setVerticalGroup(
            Ranking1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking1Layout.createSequentialGroup()
                .addGroup(Ranking1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ranking1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BtnVoltar3)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ranking1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PaneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Base.addTab("tab1", Ranking1);

        getContentPane().add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(-45, 79, 860, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCriarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarPartidaActionPerformed
        Base.setSelectedIndex(1);
    }//GEN-LAST:event_BtnCriarPartidaActionPerformed

    private void BtnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRankingActionPerformed
        Base.setSelectedIndex(5);
        UsuarioDAO uDAO = new UsuarioDAO();
        ArrayList<Usuario> usuarios = new ArrayList<>();     
        usuarios = uDAO.carregarUsuarios();
        
        DefaultTableModel modeloTabelUsuario = (DefaultTableModel)TableUsuarios.getModel();
        modeloTabelUsuario.setNumRows(0);
        for (Usuario usuario : usuarios) {
            Object[] usuarioObj ={usuario.getNome(),usuario.getPontuação(),usuario.getTotal()};            
            modeloTabelUsuario.addRow(usuarioObj);
        }
        
        TableUsuarios.setModel(modeloTabelUsuario);
    }//GEN-LAST:event_BtnRankingActionPerformed

    private void BtnCarregarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarPartidaActionPerformed
        PartidaDAO pDAO = new PartidaDAO();
        DefaultComboBoxModel modeloComboPartidas = new DefaultComboBoxModel();
        
        this.partidas = pDAO.carregarPartidas(); 
        modeloComboPartidas.addAll(partidas);
        ComboBoxPartida.setModel(modeloComboPartidas);  
        Base.setSelectedIndex(2);
    }//GEN-LAST:event_BtnCarregarPartidaActionPerformed

    private void BtnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarActionPerformed
        PartidaDAO pDAO = new PartidaDAO();
        QuestaoDAO qDAO = new QuestaoDAO();
        Partida p = (Partida)ComboBoxPartida.getSelectedItem();
        System.out.println(p.getId_partida());
        
        corretas = p.getCorretas();
        iQuestao = p.getContador();
        questoes = qDAO.carregarQuestoes(p.getQuestoes()); 
        
        Base.setSelectedIndex(3);
        CarregaQuestao();
    }//GEN-LAST:event_BtnCarregarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        Base.setSelectedIndex(0);
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarActionPerformed
        QuestaoDAO qDAO = new QuestaoDAO();
        int quantidade = (Integer)SpingQuestoes.getValue();
        int nivel = ComboBoxDificuldade.getSelectedIndex()+1;
        int tema = ComboBoxTemas.getSelectedIndex()+1;
        
        this.questoes= qDAO.cosultarQuestoesFinal(quantidade, nivel, tema);
        
        
        Base.setSelectedIndex(3);
        
        CarregaQuestao();                                            
    }//GEN-LAST:event_BtnCriarActionPerformed

    private void BtnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar2ActionPerformed
        Base.setSelectedIndex(0);
    }//GEN-LAST:event_BtnVoltar2ActionPerformed

    private void ComboBoxDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDificuldadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDificuldadeActionPerformed

    private void ComboBoxTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTemasActionPerformed

    private void RadioAlternativa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlternativa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlternativa4ActionPerformed

    private void RadioAlternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlternativa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlternativa1ActionPerformed

    private void RadioAlternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlternativa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlternativa2ActionPerformed

    private void RadioAlternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlternativa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlternativa3ActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        PartidaDAO pDAO = new PartidaDAO();
        ArrayList<Integer> idQuestoes = new ArrayList<>();
               
        for (Questao q : questoes) {
            idQuestoes.add(q.getId_questao());
        }        
        Partida p = new Partida(corretas, idQuestoes, iQuestao);
        pDAO.cadastrarPartida(p);
        
        Base.setSelectedIndex(0);
        corretas = 0;
        iQuestao = 0;
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
               
                
        CarregaQuestao();
       
        if(RadioAlternativa1.isSelected() && alt1.isCorreta())
       {
           JOptionPane.showMessageDialog(null, "Acertou");
           corretas++;
       }else if(RadioAlternativa2.isSelected() && alt2.isCorreta())
       {
           JOptionPane.showMessageDialog(null, "Acertou");
           corretas++;
       }
       else if(RadioAlternativa3.isSelected() && alt3.isCorreta())
       {
           JOptionPane.showMessageDialog(null, "Acertou");
           corretas++;
       }
       else if(RadioAlternativa4.isSelected() && alt4.isCorreta())
       {
           JOptionPane.showMessageDialog(null, "Acertou");
           corretas++;
       }
       else
            JOptionPane.showMessageDialog(null, "Errou");
        
        if(iQuestao+1 == questoes.size())
        {
            Base.setSelectedIndex(4);            
            TextPontos.setText(corretas+"/"+(questoes.size()));            
        }
        else
        {
            iQuestao++;        
            CarregaQuestao();
        }        
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void BtnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSair2ActionPerformed
    Usuario u = new Usuario(FieldNome.getText(), corretas, questoes.size());
    UsuarioDAO uDAO = new UsuarioDAO();
    
    uDAO.cadastrarUsuario(u);
                    
    corretas = 0;
    iQuestao = 0;
    Base.setSelectedIndex(0);
    }//GEN-LAST:event_BtnSair2ActionPerformed

    private void BtnVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar3ActionPerformed
        Base.setSelectedIndex(0);
    }//GEN-LAST:event_BtnVoltar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Alternativas;
    private javax.swing.JTabbedPane Base;
    private javax.swing.JButton BtnCarregar;
    private javax.swing.JButton BtnCarregarPartida;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnCriar;
    private javax.swing.JButton BtnCriarPartida;
    private javax.swing.JButton BtnRanking;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnSair2;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JButton BtnVoltar2;
    private javax.swing.JButton BtnVoltar3;
    private javax.swing.JPanel Cabecalho;
    private javax.swing.JPanel CarregarPartida;
    private javax.swing.JComboBox<String> ComboBoxDificuldade;
    private javax.swing.JComboBox<String> ComboBoxPartida;
    private javax.swing.JComboBox<String> ComboBoxTemas;
    private javax.swing.JPanel CriarPartida;
    private javax.swing.JTextField FieldNome;
    private javax.swing.JTextField FieldPergunta;
    private javax.swing.JPanel Final;
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane PaneUsuarios;
    private javax.swing.JPanel Pergunta;
    private javax.swing.JRadioButton RadioAlternativa1;
    private javax.swing.JRadioButton RadioAlternativa2;
    private javax.swing.JRadioButton RadioAlternativa3;
    private javax.swing.JRadioButton RadioAlternativa4;
    private javax.swing.JPanel Ranking1;
    private javax.swing.JSpinner SpingQuestoes;
    private javax.swing.JTable TableUsuarios;
    private javax.swing.JLabel TextPontos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
